/*
 * Created on 20 Jan 2016 ( Time 09:12:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Category implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer parentId;

    @NotNull
    @Size( min = 1, max = 255 )
    private String catName;

    @Size( max = 255 )
    private String catNameAdmin;

    @Size( max = 500 )
    private String image;


    private Date createDate;


    private Date updateDate;


    private Integer isDelete;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setParentId( Integer parentId ) {
        this.parentId = parentId;
    }
    public Integer getParentId() {
        return this.parentId;
    }

    public void setCatName( String catName ) {
        this.catName = catName;
    }
    public String getCatName() {
        return this.catName;
    }

    public void setCatNameAdmin( String catNameAdmin ) {
        this.catNameAdmin = catNameAdmin;
    }
    public String getCatNameAdmin() {
        return this.catNameAdmin;
    }

    public void setImage( String image ) {
        this.image = image;
    }
    public String getImage() {
        return this.image;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(parentId);
        sb.append("|");
        sb.append(catName);
        sb.append("|");
        sb.append(catNameAdmin);
        sb.append("|");
        sb.append(image);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(isDelete);
        return sb.toString(); 
    } 


}
