/*
 * Created on 25 Dec 2015 ( Time 11:25:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Info implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 300 )
    private String address1;

    @Size( max = 300 )
    private String address2;

    @Size( max = 40 )
    private String contactNumber;

    @Size( max = 45 )
    private String fax;

    @Size( max = 45 )
    private String email;

    @Size( max = 100 )
    private String link;


    private Integer isDelete;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAddress1( String address1 ) {
        this.address1 = address1;
    }
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress2( String address2 ) {
        this.address2 = address2;
    }
    public String getAddress2() {
        return this.address2;
    }

    public void setContactNumber( String contactNumber ) {
        this.contactNumber = contactNumber;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }

    public void setFax( String fax ) {
        this.fax = fax;
    }
    public String getFax() {
        return this.fax;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setLink( String link ) {
        this.link = link;
    }
    public String getLink() {
        return this.link;
    }

    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(address1);
        sb.append("|");
        sb.append(address2);
        sb.append("|");
        sb.append(contactNumber);
        sb.append("|");
        sb.append(fax);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(link);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
