/*
 * Created on 11 Dec 2015 ( Time 20:38:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.junggu.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "comment"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="comment", catalog="junggutwo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CommentEntity.countAll", query="SELECT COUNT(x) FROM CommentEntity x" )
} )
public class CommentEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="_id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DETAILS", nullable=false, length=1000)
    private String     details      ;

    @Column(name="USER_ID", nullable=false)
    private Integer    userId       ;

    @Column(name="USER_USERNAME", nullable=false, length=50)
    private String     userUsername ;

    @Column(name="STORE_ID", nullable=false)
    private Integer    storeId      ;

    @Column(name="GRADE")
    private Integer    grade        ;

    @Column(name="IS_DELETE")
    private Integer    isDelete     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE")
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE")
    private Date       updateDate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CommentEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DETAILS ( VARCHAR ) 
    public void setDetails( String details ) {
        this.details = details;
    }
    public String getDetails() {
        return this.details;
    }

    //--- DATABASE MAPPING : USER_ID ( INT ) 
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    //--- DATABASE MAPPING : USER_USERNAME ( VARCHAR ) 
    public void setUserUsername( String userUsername ) {
        this.userUsername = userUsername;
    }
    public String getUserUsername() {
        return this.userUsername;
    }

    //--- DATABASE MAPPING : STORE_ID ( INT ) 
    public void setStoreId( Integer storeId ) {
        this.storeId = storeId;
    }
    public Integer getStoreId() {
        return this.storeId;
    }

    //--- DATABASE MAPPING : GRADE ( INT ) 
    public void setGrade( Integer grade ) {
        this.grade = grade;
    }
    public Integer getGrade() {
        return this.grade;
    }

    //--- DATABASE MAPPING : IS_DELETE ( INT ) 
    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }

    //--- DATABASE MAPPING : CREATE_DATE ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : UPDATE_DATE ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(details);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(userUsername);
        sb.append("|");
        sb.append(storeId);
        sb.append("|");
        sb.append(grade);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
