/*
 * Created on 22 Feb 2016 ( Time 14:37:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.junggu.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "server"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="server", catalog="junggutwo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ServerEntity.countAll", query="SELECT COUNT(x) FROM ServerEntity x" )
} )
public class ServerEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="_id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NAME", nullable=false, length=2000)
    private String     name         ;

    @Column(name="URL", nullable=false, length=2000)
    private String     url          ;

    @Column(name="IMAGE", length=2000)
    private String     image        ;
    
    @Column(name="MAP", length=2000)
    private String     map        ;
    
    @Column(name="CLIENT_KEY", length=2000)
    private String     clientKey        ;

    @Column(name="DESCRIPTION")
    private String     description  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false)
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", nullable=false)
    private Date       updateDate   ;

    @Column(name="IS_DELETED", nullable=false)
    private Integer     isDeleted    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ServerEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NAME ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : URL ( VARCHAR ) 
    public void setUrl( String url ) {
        this.url = url;
    }
    public String getUrl() {
        return this.url;
    }

    //--- DATABASE MAPPING : IMAGE ( VARCHAR ) 
    public void setImage( String image ) {
        this.image = image;
    }
    public String getImage() {
        return this.image;
    }
    
    //--- DATABASE MAPPING : IMAGE ( VARCHAR ) 
    public void setMap( String map ) {
        this.map = map;
    }
    public String getMap() {
        return this.map;
    }
    
    //--- DATABASE MAPPING : IMAGE ( VARCHAR ) 
    public void setClientKey( String clientKey ) {
        this.clientKey = clientKey;
    }
    public String getClientKey() {
        return this.clientKey;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( TEXT ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : CREATE_DATE ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : UPDATE_DATE ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    //--- DATABASE MAPPING : IS_DELETED ( VARCHAR ) 
    public void setIsDeleted( Integer isDeleted ) {
        this.isDeleted = isDeleted;
    }
    public Integer getIsDeleted() {
        return this.isDeleted;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(url);
        sb.append("|");
        sb.append(image);
        // attribute 'description' not usable (type = String Long Text)
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(isDeleted);
        return sb.toString(); 
    } 

}
