/*
 * Created on 29 Oct 2015 ( Time 14:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.controller;

import java.util.List;
import java.util.ArrayList;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.junggu.web.common.AbstractController;
import org.trams.junggu.web.common.FormMode;
import org.trams.junggu.web.common.Pager;
import org.trams.junggu.web.common.Login;
import org.trams.junggu.web.common.Message;
import org.trams.junggu.web.common.MessageType;
import org.trams.junggu.bean.jpa.AccessibilityEntity;

//--- Entities
import org.trams.junggu.bean.Accessibility;

//--- Services 
import org.trams.junggu.business.service.AccessibilityService;


/**
 * Spring MVC controller for 'Accessibility' management.
 */
@Controller
@RequestMapping("/accessibility")
public class AccessibilityController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "accessibility";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 15;

	private static String nav = "accessibility";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "accessibility/form";
	private static final String JSP_LIST   = "accessibility/list";
	private static final String JSP_PAGING   = "accessibility";
	private static final String JSP_DETAIL   = "accessibility/detail";
	private static final String JSP_LOGIN   = "login";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/accessibility/create";
	private static final String SAVE_ACTION_UPDATE   = "/accessibility/update";

	//--- Main entity service
	@Resource
    private AccessibilityService accessibilityService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public AccessibilityController() {
		super(AccessibilityController.class, MAIN_ENTITY_NAME );
		log("AccessibilityController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param accessibility
	 */
	private void populateModel(Model model, Accessibility accessibility, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, accessibility);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Accessibility found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/list")
	public String list(Model model) {
		/*	if(Login.checkLogin()=="0")
			return JSP_LOGIN;
		*/
		//List<Accessibility> list = accessibilityService.findAll();
		model.addAttribute(MAIN_LIST_NAME, null);		
		return JSP_LIST;
	}

	@RequestMapping()
	public String accessibilityList(@RequestParam(value="page", defaultValue="1") Integer pageNumber, Model model) {
		
	/*	if(Login.checkLogin()=="0")
			return JSP_LOGIN;
	*/
		Page<AccessibilityEntity> listPage = accessibilityService.findAll(pageNumber);
		
		model.addAttribute("activePage", nav);
		
		new Pager<AccessibilityEntity>(listPage).setSetting(model, "");	
		
		return JSP_PAGING;
	}


	@RequestMapping("/detail/{id}")
	public String detail(Model model, @PathVariable("id") Integer id) {
		
		Accessibility accessibility = accessibilityService.findById(id);
		model.addAttribute("accessibility", accessibility);
		return JSP_DETAIL;
	}
	/**
	 * Shows a form page in order to create a new Accessibility
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
	if(Login.checkLogin()=="0")
			return JSP_LOGIN;
	
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Accessibility accessibility = new Accessibility();
		populateModel( model, accessibility, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Accessibility
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
	if(Login.checkLogin()=="0")
			return JSP_LOGIN;
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Accessibility accessibility = accessibilityService.findById(id);
		populateModel( model, accessibility, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param accessibility  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Accessibility accessibility, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		if(Login.checkLogin()=="0")
			return JSP_LOGIN;
		try {
			if (!bindingResult.hasErrors()) {
				Accessibility accessibilityCreated = accessibilityService.create(accessibility); 
				model.addAttribute(MAIN_ENTITY_NAME, accessibilityCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, accessibility.getId() );
			} else {
				populateModel( model, accessibility, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "accessibility.error.create", e);
			populateModel( model, accessibility, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param accessibility  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Accessibility accessibility, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		if(Login.checkLogin()=="0")
			return JSP_LOGIN;
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Accessibility accessibilitySaved = accessibilityService.update(accessibility);
				model.addAttribute(MAIN_ENTITY_NAME, accessibilitySaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, accessibility.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, accessibility, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "accessibility.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, accessibility, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {

		if(Login.checkLogin()=="0")
			return JSP_LOGIN;
		log("Action 'delete'" );
		try {
			accessibilityService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "accessibility.error.delete", e);
		}
		return redirectToList();
	}

}
