/*
 * Created on 29 Oct 2015 ( Time 14:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.junggu.web.common.AbstractController;
import org.trams.junggu.web.common.FormMode;
import org.trams.junggu.web.common.Pager;
import org.trams.junggu.web.common.Login;
import org.trams.junggu.web.common.Message;
import org.trams.junggu.web.common.MessageType;
import org.trams.junggu.bean.jpa.CategoryEntity;
import org.trams.junggu.bean.jpa.CategoryEntity;
//--- Entities
import org.trams.junggu.bean.Category;
import org.trams.junggu.bean.Category;
//--- Services 
import org.trams.junggu.business.service.CategoryService;
import org.trams.junggu.rest.item.UserItem;


/**
 * Spring MVC controller for 'Category' management.
 */
@Controller
@RequestMapping("/category")
public class CategoryController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "category";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 15;

	private static String nav = "category";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "category/create";
	private static final String JSP_DETAIL   = "category/detail";
	private static final String JSP_LIST   = "category/list";
	private static final String JSP_PAGING   = "category";
	private static final String JSP_LOGIN   = "login";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/category/create";
	private static final String SAVE_ACTION_UPDATE   = "/category/update";

	//--- Main entity service
	@Resource
    private CategoryService categoryService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public CategoryController() {
		super(CategoryController.class, MAIN_ENTITY_NAME );
		log("CategoryController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------



	@RequestMapping("/list")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page, 
			@RequestParam(value="search",defaultValue="0") Integer search, 
			@RequestParam(value="key",defaultValue="") String key, 
			HttpSession session,
			Model model) {
		if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		if(key==null){
			key="";
		}
		if(search==1){
			page=1;
		}
		Page<CategoryEntity> listPage=categoryService.listPaging("%"+key+"%",page, PAGE_SIZE);
		model.addAttribute("activePage", nav);
		model.addAttribute("key", key);
		model.addAttribute("pagination_navigator", "/category/list");
		new Pager<CategoryEntity>(listPage).setSetting(model, "key="+key+"&amp;");	
		return JSP_LIST;
	}


	@RequestMapping("/create")
	public String create(
			@RequestParam(value="catName",defaultValue="") String catName,
			@RequestParam(value="catNameAdmin",defaultValue="") String catNameAdmin, 
			@RequestParam(value="image",defaultValue="") String image, 
			@RequestParam(value="parentId",defaultValue="0") Integer parentId, 
			@RequestParam(value="create",defaultValue="0") Integer create,
			HttpSession session,
			Model model) {
		if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		List<CategoryEntity> list= categoryService.findByGroupId(0);
		if(list!=null){
			model.addAttribute("list", list);
		}
		
		if(create>0){
			try{
				if(catName!=null && catNameAdmin!=null){
				Category category= new Category();
				category.setCatName(catName);
				category.setCatNameAdmin(catNameAdmin);
				category.setImage(image);
				category.setParentId(parentId);
				category.setUpdateDate(new Date());
				category.setCreateDate(new Date());
				category.setIsDelete(0);
				categoryService.create(category);
				return "redirect:/category/list";
				}
			}catch(Exception e){
				System.out.println(e);
				
			}
		}
		
		return JSP_CREATE;
	}
	
	@RequestMapping("/detail/{id}")
	public String detail(
			@RequestParam(value="catName",defaultValue="") String catName,
			@RequestParam(value="catNameAdmin",defaultValue="") String catNameAdmin, 
			@RequestParam(value="image",defaultValue="") String image, 
			@RequestParam(value="parentId",defaultValue="0") Integer parentId, 
			@RequestParam(value="edit",defaultValue="0") Integer edit,
			@PathVariable("id") Integer id,
			HttpSession session,
			Model model) {
		if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		List<CategoryEntity> list= categoryService.findByGroupId(0);
		if(list!=null){
			model.addAttribute("list", list);
		}
		Category category=categoryService.findById(id);
		if(edit>0){
			try{
				if(catName!=null && catNameAdmin!=null){
				category.setCatName(catName);
				category.setCatNameAdmin(catNameAdmin);
				category.setImage(image);
				category.setParentId(parentId);
				category.setUpdateDate(new Date());
				category.setCreateDate(new Date());
				category.setIsDelete(0);
				categoryService.create(category);
				return "redirect:/category/list";
				}
			}catch(Exception e){
				System.out.println(e);
				
			}
		}
		model.addAttribute("c", category);
		return JSP_DETAIL;
	}



}
