/*
 * Created on 29 Oct 2015 ( Time 14:20:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.junggu.web.common.AbstractController;
import org.trams.junggu.web.common.FormMode;
import org.trams.junggu.web.common.Pager;
import org.trams.junggu.web.common.Utils;
import org.trams.junggu.web.common.Login;
import org.trams.junggu.web.common.Message;
import org.trams.junggu.web.common.MessageType;
import org.trams.junggu.bean.jpa.CommentEntity;
import org.trams.junggu.bean.jpa.StoreEntity;
import org.trams.junggu.bean.jpa.UserEntity;

//--- Entities
import org.trams.junggu.bean.User;
import org.trams.junggu.business.service.CommentService;
//--- Services 
import org.trams.junggu.business.service.UserService;


/**
 * Spring MVC controller for 'User' management.
 */
@Controller
@RequestMapping("/member")
public class UserController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "user";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 10;

	private static String nav = "member";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "member/form";
	private static final String JSP_LIST   = "member/list";
	private static final String JSP_PAGING   = "member";
	private static final String JSP_DETAIL   = "member/detail";
	private static final String JSP_LOGIN   = "login";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/member/create";
	private static final String SAVE_ACTION_UPDATE   = "/member/update";

	//--- Main entity service
	@Resource
    private UserService userService; // Injected by Spring
	@Resource
    private CommentService commentService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	
	public UserController() {
		super(UserController.class, MAIN_ENTITY_NAME );
		log("UserController created.");
	}

	@RequestMapping("/list")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="type",defaultValue="id") String type,
			@RequestParam(value="key",defaultValue="") String key,
			@RequestParam(value="search",defaultValue="0") Integer search,
			@RequestParam(value="delete",defaultValue="0") Integer delete,
			Model model,HttpSession session) {
		if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		Page<UserEntity> listPage=null;
		String strKey="";
		if(delete>0){
			try {
				User user=userService.findById(delete);
				user.setIsDelete(1);;
				user.setUpdateDate(new Date());
				userService.update(user);
			} catch (Exception e) {
				
			}
		}
		if(search>0 && key!="" && key!=null){
			strKey=key;
			if (type.equalsIgnoreCase("id")) {
				listPage=userService.findAllById(key, page, PAGE_SIZE);
			}else if (type.equalsIgnoreCase("mobile")) {
				listPage=userService.findAllByMobileNumber(key, page, PAGE_SIZE);
			}else{
				listPage=userService.listPaging(page, PAGE_SIZE);
			}
		}else{
			listPage=userService.listPaging(page, PAGE_SIZE);
		}
		model.addAttribute("key", strKey);
		model.addAttribute("type", type);
		model.addAttribute("activePage", nav);
		model.addAttribute("pagination_navigator", "/member/list");
		new Pager<UserEntity>(listPage).setSetting(model, "type="+type+"&amp;key="+strKey+"&amp;");	
		return JSP_LIST;
	}
	@RequestMapping("/detail/{id}")
	public String detail(
			@RequestParam(value="password1",defaultValue="1") String password1,
			@RequestParam(value="password2",defaultValue="1") String password2,
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="edit",defaultValue="0") Integer edit,
			@RequestParam(value="delete",defaultValue="0") Integer delete,
			@PathVariable("id") Integer id,
			Model model,HttpSession session) {
		if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		User user = userService.findById(id);
		if(delete>0){
			commentService.delete(delete);
		}
		if(edit>0){
			if(password1==password2 && password1!="" && password2!="" ){
				user.setPassword(password1);
				userService.update(user);
			}
		}
		Page<CommentEntity> list = commentService.findAllByUser(id, page, 5);
		model.addAttribute("user",user);
		model.addAttribute("activePage", nav);

		new Pager<CommentEntity>(list).setSetting(model, "");	
		return JSP_DETAIL;
	}
	
}
