/*
 * Created on 11 Dec 2015 ( Time 17:33:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
