/*
 * Created on 29 Oct 2015 ( Time 14:20:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.rest.controller;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.junggu.bean.Accessibility;
import org.trams.junggu.bean.Category;
import org.trams.junggu.bean.User;
import org.trams.junggu.bean.jpa.AccessibilityEntity;
import org.trams.junggu.bean.jpa.UserEntity;
import org.trams.junggu.business.service.AccessibilityService;
import org.trams.junggu.rest.common.Message;
import org.trams.junggu.rest.common.ReturnValue;
import org.trams.junggu.web.common.Utils;
import org.trams.junggu.web.listitem.AccessibilityListItem;

/**
 * Spring MVC controller for 'Accessibility' management.
 */
@Controller
public class AccessibilityRestController {

	@Resource
	private AccessibilityService accessibilityService;
//	
//	@RequestMapping( value="/items/accessibility",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public List<AccessibilityListItem> findAllAsListItems() {
//		List<Accessibility> list = accessibilityService.findAll();
//		List<AccessibilityListItem> items = new LinkedList<AccessibilityListItem>();
//		for ( Accessibility accessibility : list ) {
//			items.add(new AccessibilityListItem( accessibility ) );
//		}
//		return items;
//	}
	
	@RequestMapping( value="/items/accessibility",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturnValue findAllAsListItems(@RequestBody String json) {
		
		ReturnValue rv =  new ReturnValue();
		try {
			
		JSONParser parser = new JSONParser();
		JSONObject jsonObj = (JSONObject) parser.parse(json);
		Long updateDate = org.trams.junggu.web.common.Utils.parseLong(jsonObj.get("updateDate"));
		Date dateUpdate = new Date(updateDate);
		List<Accessibility> list = accessibilityService.findAllUpdate(dateUpdate);
		if(list.size()>0)
		rv.ReturningObject(list);
		else
			rv.ReturningString(Message.LIST_UPDATE_FAIL, Message.LIST_UPDATE_ZERO_CODE);
		return rv;
		} catch(Exception e)
		{
			rv.ReturningException();
			return rv;
		}
		
	}
//	
//	@RequestMapping( value="/accessibility",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public List<Accessibility> findAll() {
//		return accessibilityService.findAll();
//	}
//
//	@RequestMapping( value="/accessibility/{id}",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Accessibility findOne(@PathVariable("id") Integer id) {
//		return accessibilityService.findById(id);
//	}
	
//	@RequestMapping( value="/accessibility",
//			method = RequestMethod.POST,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public ReturnValue create(@RequestBody Accessibility accessibility) {
//		Accessibility result = new Accessibility();
//		ReturnValue rv =  new ReturnValue();
//		AccessibilityEntity checkAccessibilityname = accessibilityService.finByAccessibilityName(accessibility.getName());
//	    try{
//			    if(checkAccessibilityname != null)
//			    {
//			    	rv.ReturningString(Message.DUPLICATE_ERROR, Message.DUPLICATE_ERROR_CODE);
//		    		return rv;
//			    }
//			    else
//			    	accessibility.setName(accessibility.getName());
//			    	accessibility.setDescription(accessibility.getDescription());
//			    	accessibility.setCreateDate(new Date());
//			    	accessibility.setUpdateDate(new Date());
//			    	result = accessibilityService.create(accessibility);
//			  
//	    		if(result != null)
//					rv.ReturningValue(result,Message.CREATE_ACCESSIBILITY_SUCCESS,Message.SUCCESS_CODE);
//				
//	    		return rv;
//			
//	    	} catch (Exception e)
//			{
//	    		rv.ReturningException();
//				return rv;
//			}
//	}
//
//	@RequestMapping( value="/accessibility/{id}",
//			method = RequestMethod.PUT,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Accessibility update(@PathVariable("id") Integer id, @RequestBody Accessibility accessibility) {
//		return accessibilityService.update(accessibility);
//	}
//
//	@RequestMapping( value="/accessibility/{id}",
//			method = RequestMethod.DELETE,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public void delete(@PathVariable("id") Integer id) {
//		accessibilityService.delete(id);
//	}
	
}
