/*
 * Created on 29 Oct 2015 ( Time 14:20:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.rest.controller;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.junggu.bean.Accessibility;
import org.trams.junggu.bean.Field;
import org.trams.junggu.business.service.FieldService;
import org.trams.junggu.rest.common.Message;
import org.trams.junggu.rest.common.ReturnValue;
import org.trams.junggu.web.listitem.FieldListItem;

/**
 * Spring MVC controller for 'Field' management.
 */
@Controller
public class FieldRestController {

	@Resource
	private FieldService fieldService;
	
//	@RequestMapping( value="/items/field",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public List<FieldListItem> findAllAsListItems() {
//		List<Field> list = fieldService.findAll();
//		List<FieldListItem> items = new LinkedList<FieldListItem>();
//		for ( Field field : list ) {
//			items.add(new FieldListItem( field ) );
//		}
//		return items;
//	}
	
	
	@RequestMapping( value="/items/field",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturnValue findAllAsListItems(@RequestBody String json) {
		ReturnValue rv =  new ReturnValue();
		
		try {
			JSONParser parser = new JSONParser();
			JSONObject jsonObj = (JSONObject) parser.parse(json);
			Long updateDate = org.trams.junggu.web.common.Utils.parseLong(jsonObj.get("updateDate"));
				
			Date dateUpdate = new Date(updateDate);
			
			List<Field> list = fieldService.findAllUpdate(dateUpdate);
			if(list.size()>0)
				rv.ReturningObject(list);
				else
					rv.ReturningString(Message.LIST_UPDATE_FAIL, Message.LIST_UPDATE_ZERO_CODE);
				return rv;
			} catch(Exception e){
				rv.ReturningException();
				return rv;
			}
	}

//	@RequestMapping( value="/field",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public List<Field> findAll() {
//		return fieldService.findAll();
//	}
//
//	@RequestMapping( value="/field/{id}",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Field findOne(@PathVariable("id") Integer id) {
//		return fieldService.findById(id);
//	}
//	
//	@RequestMapping( value="/field",
//			method = RequestMethod.POST,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Field create(@RequestBody Field field) {
//		return fieldService.create(field);
//	}
//
//	@RequestMapping( value="/field/{id}",
//			method = RequestMethod.PUT,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Field update(@PathVariable("id") Integer id, @RequestBody Field field) {
//		return fieldService.update(field);
//	}
//
//	@RequestMapping( value="/field/{id}",
//			method = RequestMethod.DELETE,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public void delete(@PathVariable("id") Integer id) {
//		fieldService.delete(id);
//	}
	
}
