/*
 * Created on 25 Dec 2015 ( Time 11:25:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.rest.controller;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpSession;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.junggu.bean.Field;
import org.trams.junggu.bean.Info;
import org.trams.junggu.bean.Intro;
import org.trams.junggu.business.service.InfoService;
import org.trams.junggu.rest.common.Message;
import org.trams.junggu.rest.common.ReturnValue;
import org.trams.junggu.web.listitem.InfoListItem;

/**
 * Spring MVC controller for 'Info' management.
 */
@Controller
public class InfoRestController {

	@Resource
	private InfoService infoService;
	
	@RequestMapping( value="/api/info",		
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturnValue getImage(HttpSession session) {
		ReturnValue rv = new ReturnValue();
		try {
			//UserItem user = Login.getUserLogined(session);
			
				List<Info> list =infoService.findAll();
				
				rv.ReturningObject(list);				
				
					return rv;
			
		} catch (Exception e) {
			 rv.ReturningException();
			 return rv;
		}
		
		
	}
	
	@RequestMapping( value="/items/info",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturnValue findAllAsListItems(@RequestBody String json) {
		ReturnValue rv =  new ReturnValue();
		
		try {
			JSONParser parser = new JSONParser();
			JSONObject jsonObj = (JSONObject) parser.parse(json);
			Long updateDate = org.trams.junggu.web.common.Utils.parseLong(jsonObj.get("updateDate"));
				
			Date dateUpdate = new Date(updateDate);
			
			List<Info> list = infoService.findAllUpdate(dateUpdate);
			if(list.size()>0)
				rv.ReturningObject(list);
				else
					rv.ReturningString(Message.LIST_UPDATE_FAIL, Message.LIST_UPDATE_ZERO_CODE);
				return rv;
			} catch(Exception e){
				rv.ReturningException();
				return rv;
			}
	}
	
}
