/*
 * Created on 10 Dec 2015 ( Time 15:21:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.rest.controller;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpSession;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.junggu.bean.Intro;
import org.trams.junggu.bean.Report;
import org.trams.junggu.bean.jpa.ReportEntity;
import org.trams.junggu.business.service.IntroService;
import org.trams.junggu.rest.common.Message;
import org.trams.junggu.rest.common.ReturnValue;
import org.trams.junggu.rest.item.UserItem;
import org.trams.junggu.web.common.Login;
import org.trams.junggu.web.listitem.IntroListItem;

/**
 * Spring MVC controller for 'Intro' management.
 */
@Controller
public class IntroRestController {

	@Resource
	private IntroService introService;
	
	@RequestMapping( value="/api/intro",		
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturnValue getImage(HttpSession session) {
		ReturnValue rv = new ReturnValue();
		try {
			//UserItem user = Login.getUserLogined(session);
			
				List<Intro> list =introService.findAll();
				
				rv.ReturningObject(list);				
				
					return rv;
			
		} catch (Exception e) {
			 rv.ReturningException();
			 return rv;
		}
		
		
	}
	
}
