/*
 * Created on 29 Oct 2015 ( Time 14:20:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.rest.controller;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.junggu.bean.Notice;
import org.trams.junggu.business.service.NoticeService;
import org.trams.junggu.rest.common.Message;
import org.trams.junggu.rest.common.ReturnValue;
import org.trams.junggu.web.listitem.NoticeListItem;

/**
 * Spring MVC controller for 'Notice' management.
 */
@Controller
public class NoticeRestController {

	@Resource
	private NoticeService noticeService;
	
//	@RequestMapping( value="/items/notice",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public List<NoticeListItem> findAllAsListItems() {
//		List<Notice> list = noticeService.findAll();
//		List<NoticeListItem> items = new LinkedList<NoticeListItem>();
//		for ( Notice notice : list ) {
//			items.add(new NoticeListItem( notice ) );
//		}
//		return items;
//	}
	
	@RequestMapping( value="/items/notice",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ReturnValue findAllAsListItems(@RequestBody String json) {
		ReturnValue rv =  new ReturnValue();
		
		try {
			
		JSONParser parser = new JSONParser();
		JSONObject jsonObj = (JSONObject) parser.parse(json);
		Long updateDate = org.trams.junggu.web.common.Utils.parseLong(jsonObj.get("updateDate"));
			
		Date dateUpdate = new Date(updateDate);
		
		List<Notice> list = noticeService.findAllUpdate(dateUpdate);
		if(list.size()>0)
		rv.ReturningObject(list);
		else
			rv.ReturningString(Message.LIST_UPDATE_FAIL, Message.LIST_UPDATE_ZERO_CODE);
		return rv;
		} catch(Exception e)
		{
			rv.ReturningException();
			return rv;
		}
	}
//	
//	@RequestMapping( value="/notice",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public List<Notice> findAll() {
//		return noticeService.findAll();
//	}
//
//	@RequestMapping( value="/notice/{id}",
//			method = RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Notice findOne(@PathVariable("id") Integer id) {
//		return noticeService.findById(id);
//	}
//	
//	@RequestMapping( value="/notice",
//			method = RequestMethod.POST,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Notice create(@RequestBody Notice notice) {
//		return noticeService.create(notice);
//	}
//
//	@RequestMapping( value="/notice/{id}",
//			method = RequestMethod.PUT,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public Notice update(@PathVariable("id") Integer id, @RequestBody Notice notice) {
//		return noticeService.update(notice);
//	}
//
//	@RequestMapping( value="/notice/{id}",
//			method = RequestMethod.DELETE,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//    @ResponseStatus(HttpStatus.OK)
//	@ResponseBody
//	public void delete(@PathVariable("id") Integer id) {
//		noticeService.delete(id);
//	}
	
}
