/*
 * Created on 29 Oct 2015 ( Time 14:22:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.AccessibilityEntity;
import org.trams.junggu.bean.Accessibility;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Accessibility.
 */
public interface AccessibilityService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Accessibility findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Accessibility> findAll();
	List<Accessibility> findAllUpdate(Date updateDate);
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<AccessibilityEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Accessibility save(Accessibility entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Accessibility update(Accessibility entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Accessibility create(Accessibility entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	AccessibilityEntity finByAccessibilityName(String name);


}
