/*
 * Created on 9 Nov 2015 ( Time 12:45:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.CommentEntity;
import org.trams.junggu.bean.Comment;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Comment.
 */
public interface CommentService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Comment findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Comment> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CommentEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Comment save(Comment entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Comment update(Comment entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Comment create(Comment entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	CommentEntity checkExitsComment(Integer userId, Integer storeId);

	List<Integer[]> getSumGradeByStoreId(int storeId);

	List<CommentEntity> finAllUpdate(Date updateDate);

	List<CommentEntity> findAllByUser(Integer id);
	Page<CommentEntity> findAllByUser(Integer id, Integer page, Integer size);
	Page<CommentEntity> findAllByStore(Integer storeId, Integer page, Integer size);
	List<CommentEntity> findAllByStore(Integer storeId);
	Integer totalComment_ByStoreId(Integer storeId);
}
