/*
 * Created on 29 Oct 2015 ( Time 14:22:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.FacilityEntity;
import org.trams.junggu.bean.Facility;
import org.trams.junggu.bean.Version;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Facility.
 */
public interface FacilityService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Facility findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Facility> findAll();
	List<Facility> findAllUpdate(Date updateDate);
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<FacilityEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Facility save(Facility entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Facility update(Facility entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Facility create(Facility entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	Page<FacilityEntity> listPaging(String key,Integer page, Integer size);

}
