/*
 * Created on 29 Oct 2015 ( Time 14:22:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.FieldEntity;
import org.trams.junggu.bean.Field;
import org.trams.junggu.bean.Version;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity Field.
 */
public interface FieldService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Field findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Field> findAll();
	List<Field> findAllUpdate(Date updateDate);
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<FieldEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Field save(Field entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Field update(Field entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Field create(Field entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	List<FieldEntity> listField();
	Page<FieldEntity> listPaging(String key,Integer page,Integer size);
}
