/*
 * Created on 25 Dec 2015 ( Time 11:25:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.InfoEntity;
import org.trams.junggu.bean.Info;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Info.
 */
public interface InfoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Info findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Info> findAll();
	List<Info> findAllUpdate(Date updateDate);
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<InfoEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Info save(Info entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Info update(Info entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Info create(Info entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
