/*
 * Created on 22 Feb 2016 ( Time 14:37:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.ServerEntity;
import org.trams.junggu.bean.Server;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Server.
 */
public interface ServerService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Server findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Server> findAll();
	List<Server> findAllUpdate(Date updateDate);
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ServerEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Server save(Server entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Server update(Server entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Server create(Server entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
