/*
 * Created on 5 Nov 2015 ( Time 17:13:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Collection;
import java.util.Date;
import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.junggu.bean.Store;
import org.trams.junggu.bean.jpa.StoreEntity;

/**
 * Business Service Interface for entity Store.
 */
public interface StoreService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Store findById( Integer id  ) ;

	/**
	 * thienth 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Store> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */
	List<Store> findAll(Integer page);
	List<Store> findAllUpdate(Date updateDate);
	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Store save(Store entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Store update(Store entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Store create(Store entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	Page<StoreEntity> listPaging(Integer page, Integer size);
	Page<StoreEntity> findALlByCompanyName(String name, Integer page, Integer size);
	Page<StoreEntity> findALlByAdress(String address, Integer page, Integer size) ;
	Page<StoreEntity> findALlByRepresentative(String representative, Integer page, Integer size);
	Page<StoreEntity> findALlByMainPhone(String phone, Integer page, Integer size);
	Page<StoreEntity> findALlByCategory(String catid, Integer page, Integer size);
	String getNameStore(Integer id);
}
