/*
 * Created on 29 Oct 2015 ( Time 14:22:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.UserEntity;
import org.trams.junggu.bean.User;
import org.trams.junggu.bean.Version;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity User.
 */
public interface UserService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	User findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<User> findAll();
	
	List<User> findAllUpdate(Date updateDate);
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<UserEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	User save(User entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	User update(User entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	User create(User entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	UserEntity login(String username,String password, Integer role);
	
	UserEntity findByUserName(String username);
	
	Page<UserEntity> listPaging(Integer page, Integer size);
	
	Page<UserEntity> findAllById(String id,Integer page, Integer size);
	
	Page<UserEntity> findAllByMobileNumber(String phone,Integer page, Integer size);

}
