/*
 * Created on 29 Oct 2015 ( Time 14:22:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service;

import java.util.Date;
import java.util.List;
import org.trams.junggu.bean.jpa.VersionEntity;
import org.trams.junggu.bean.Version;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Version.
 */
public interface VersionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Version findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Version> findAll();
	List<Version> findAllUpdate(Date updateDate);
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<VersionEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Version save(Version entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Version update(Version entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Version create(Version entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
