/*
 * Created on 9 Nov 2015 ( Time 12:45:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.trams.junggu.bean.Report;
import org.trams.junggu.bean.jpa.ReportEntity;
import java.util.Date;
import org.trams.junggu.business.service.ReportService;
import org.trams.junggu.business.service.mapping.ReportServiceMapper;
import org.trams.junggu.data.repository.jpa.ReportJpaRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.domain.Sort.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of ReportService
 */
@Component
@Transactional
public class ReportServiceImpl implements ReportService {

	@Resource
	private ReportJpaRepository reportJpaRepository;

	private static final Integer PAGE_SIZE   = 15;

	@Resource
	private ReportServiceMapper reportServiceMapper;
	
	@Override
	public Report findById(Integer id) {
		ReportEntity reportEntity = reportJpaRepository.findOne(id);
		return reportServiceMapper.mapReportEntityToReport(reportEntity);
	}

	@Override
	public Page<ReportEntity> findAll(Integer pageNumber) {

		PageRequest request = new PageRequest(pageNumber - 1, PAGE_SIZE,
				new Sort(new Order(Direction.DESC, "id")));
		return reportJpaRepository.findAll(request);
	}

	@Override
	public List<Report> findAll() {
		Iterable<ReportEntity> entities = reportJpaRepository.findAll();
		List<Report> beans = new ArrayList<Report>();
		for(ReportEntity reportEntity : entities) {
			beans.add(reportServiceMapper.mapReportEntityToReport(reportEntity));
		}
		return beans;
	}

	/**
	 * Count total entit
	 * @return Long
	 */
	public Long countTotal(){
		Long count = reportJpaRepository.count();
		return count;
	}

	@Override
	public Report save(Report report) {
		return update(report) ;
	}

	@Override
	public Report create(Report report) {
/*
		ReportEntity reportEntity = reportJpaRepository.findOne(report.getId());
		if( reportEntity != null ) {
			throw new IllegalStateException("already.exists");
		}

		reportEntity = new ReportEntity();
		reportServiceMapper.mapReportToReportEntity(report, reportEntity);
		ReportEntity reportEntitySaved = reportJpaRepository.save(reportEntity);
		return reportServiceMapper.mapReportEntityToReport(reportEntitySaved);
*/
		ReportEntity reportEntity = new ReportEntity();
		reportServiceMapper.mapReportToReportEntity(report, reportEntity);
		ReportEntity reportEntitySaved = reportJpaRepository.save(reportEntity);
		return reportServiceMapper.mapReportEntityToReport(reportEntitySaved);
	}

	@Override
	public Report update(Report report) {
		ReportEntity reportEntity = reportJpaRepository.findOne(report.getId());
		reportServiceMapper.mapReportToReportEntity(report, reportEntity);
		ReportEntity reportEntitySaved = reportJpaRepository.save(reportEntity);
		return reportServiceMapper.mapReportEntityToReport(reportEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		reportJpaRepository.delete(id);
	}

	public ReportJpaRepository getReportJpaRepository() {
		return reportJpaRepository;
	}

	public void setReportJpaRepository(ReportJpaRepository reportJpaRepository) {
		this.reportJpaRepository = reportJpaRepository;
	}

	public ReportServiceMapper getReportServiceMapper() {
		return reportServiceMapper;
	}

	public void setReportServiceMapper(ReportServiceMapper reportServiceMapper) {
		this.reportServiceMapper = reportServiceMapper;
	}

	@Override
	public Page<ReportEntity> listPaging(Integer page, Integer size) {
		try {
			PageRequest pageable = new PageRequest(page-1, size, new Sort(new Order(Direction.DESC, "id")));
			return reportJpaRepository.listPaging(pageable);
		} catch (Exception e) {
			return null;
		}
		
	}

	@Override
	public ReportEntity findByStoreReporter(Integer userId, String phoneNumber) {
		try {
			return reportJpaRepository.findByStoreReporter(userId,phoneNumber);
		} catch (Exception e) {
			return null;
		}
	}

	@Override
	public ReportEntity findByStoreReporter(Integer userId, Integer storeId) {
		try {
			return reportJpaRepository.findByStoreReporter(userId,storeId);
		} catch (Exception e) {
			return null;
		}
	}
	@Override
	public List<ReportEntity> listByStoreReporter(Integer userId, Integer storeId) {
		try {
		
			return reportJpaRepository.listByStoreReporter(userId,storeId);
		} catch (Exception e) {
			return null;
		}
	}

	@Override
	public List<ReportEntity> listByStore(Integer storeId) {
		try {
			
			return reportJpaRepository.listByStore(storeId);
		} catch (Exception e) {
			return null;
		}
	}
	

}
