/*
 * Created on 11 Dec 2015 ( Time 20:38:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Accessibility;
import org.trams.junggu.bean.jpa.AccessibilityEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AccessibilityServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AccessibilityServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AccessibilityEntity' to 'Accessibility'
	 * @param accessibilityEntity
	 */
	public Accessibility mapAccessibilityEntityToAccessibility(AccessibilityEntity accessibilityEntity) {
		if(accessibilityEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Accessibility accessibility = map(accessibilityEntity, Accessibility.class);

		return accessibility;
	}
	
	/**
	 * Mapping from 'Accessibility' to 'AccessibilityEntity'
	 * @param accessibility
	 * @param accessibilityEntity
	 */
	public void mapAccessibilityToAccessibilityEntity(Accessibility accessibility, AccessibilityEntity accessibilityEntity) {
		if(accessibility == null) {
			return;
		}

		//--- Generic mapping 
		map(accessibility, accessibilityEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}