/*
 * Created on 11 Dec 2015 ( Time 20:38:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Comment;
import org.trams.junggu.bean.jpa.CommentEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CommentServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CommentServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CommentEntity' to 'Comment'
	 * @param commentEntity
	 */
	public Comment mapCommentEntityToComment(CommentEntity commentEntity) {
		if(commentEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Comment comment = map(commentEntity, Comment.class);

		return comment;
	}
	
	/**
	 * Mapping from 'Comment' to 'CommentEntity'
	 * @param comment
	 * @param commentEntity
	 */
	public void mapCommentToCommentEntity(Comment comment, CommentEntity commentEntity) {
		if(comment == null) {
			return;
		}

		//--- Generic mapping 
		map(comment, commentEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}