/*
 * Created on 25 Dec 2015 ( Time 11:25:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Info;
import org.trams.junggu.bean.jpa.InfoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class InfoServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public InfoServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'InfoEntity' to 'Info'
	 * @param infoEntity
	 */
	public Info mapInfoEntityToInfo(InfoEntity infoEntity) {
		if(infoEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Info info = map(infoEntity, Info.class);

		return info;
	}
	
	/**
	 * Mapping from 'Info' to 'InfoEntity'
	 * @param info
	 * @param infoEntity
	 */
	public void mapInfoToInfoEntity(Info info, InfoEntity infoEntity) {
		if(info == null) {
			return;
		}

		//--- Generic mapping 
		map(info, infoEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}