/*
 * Created on 11 Dec 2015 ( Time 20:38:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Notice;
import org.trams.junggu.bean.jpa.NoticeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class NoticeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public NoticeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'NoticeEntity' to 'Notice'
	 * @param noticeEntity
	 */
	public Notice mapNoticeEntityToNotice(NoticeEntity noticeEntity) {
		if(noticeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Notice notice = map(noticeEntity, Notice.class);

		return notice;
	}
	
	/**
	 * Mapping from 'Notice' to 'NoticeEntity'
	 * @param notice
	 * @param noticeEntity
	 */
	public void mapNoticeToNoticeEntity(Notice notice, NoticeEntity noticeEntity) {
		if(notice == null) {
			return;
		}

		//--- Generic mapping 
		map(notice, noticeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}