/*
 * Created on 11 Dec 2015 ( Time 20:38:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Report;
import org.trams.junggu.bean.jpa.ReportEntity;
import org.trams.junggu.bean.jpa.StoreEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ReportServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ReportServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ReportEntity' to 'Report'
	 * @param reportEntity
	 */
	public Report mapReportEntityToReport(ReportEntity reportEntity) {
		if(reportEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Report report = map(reportEntity, Report.class);

		//--- Link mapping ( link to Store )
		if(reportEntity.getStore() != null) {
			report.setStoreId(reportEntity.getStore().getId());
		}
		return report;
	}
	
	/**
	 * Mapping from 'Report' to 'ReportEntity'
	 * @param report
	 * @param reportEntity
	 */
	public void mapReportToReportEntity(Report report, ReportEntity reportEntity) {
		if(report == null) {
			return;
		}

		//--- Generic mapping 
		map(report, reportEntity);

		//--- Link mapping ( link : report )
		if( hasLinkToStore(report) ) {
			StoreEntity store1 = new StoreEntity();
			store1.setId( report.getStoreId() );
			reportEntity.setStore( store1 );
		} else {
			reportEntity.setStore( null );
		}

	}
	
	/**
	 * Verify that Store id is valid.
	 * @param Store Store
	 * @return boolean
	 */
	private boolean hasLinkToStore(Report report) {
		if(report.getStoreId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}