/*
 * Created on 22 Feb 2016 ( Time 14:37:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Server;
import org.trams.junggu.bean.jpa.ServerEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ServerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ServerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ServerEntity' to 'Server'
	 * @param serverEntity
	 */
	public Server mapServerEntityToServer(ServerEntity serverEntity) {
		if(serverEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Server server = map(serverEntity, Server.class);

		return server;
	}
	
	/**
	 * Mapping from 'Server' to 'ServerEntity'
	 * @param server
	 * @param serverEntity
	 */
	public void mapServerToServerEntity(Server server, ServerEntity serverEntity) {
		if(server == null) {
			return;
		}

		//--- Generic mapping 
		map(server, serverEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}