/*
 * Created on 11 Dec 2015 ( Time 20:38:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.junggu.bean.Version;
import org.trams.junggu.bean.jpa.VersionEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class VersionServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public VersionServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'VersionEntity' to 'Version'
	 * @param versionEntity
	 */
	public Version mapVersionEntityToVersion(VersionEntity versionEntity) {
		if(versionEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Version version = map(versionEntity, Version.class);

		return version;
	}
	
	/**
	 * Mapping from 'Version' to 'VersionEntity'
	 * @param version
	 * @param versionEntity
	 */
	public void mapVersionToVersionEntity(Version version, VersionEntity versionEntity) {
		if(version == null) {
			return;
		}

		//--- Generic mapping 
		map(version, versionEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}