/*
 * Created on 20 Jan 2016 ( Time 09:17:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.listitem;

import org.trams.junggu.bean.Category;
import org.trams.junggu.web.common.ListItem;

public class CategoryListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CategoryListItem(Category category) {
		super();

		this.value = ""
			 + category.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = category.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
