/*
 * Created on 25 Dec 2015 ( Time 11:25:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.listitem;

import org.trams.junggu.bean.Info;
import org.trams.junggu.web.common.ListItem;

public class InfoListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public InfoListItem(Info info) {
		super();

		this.value = ""
			 + info.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = info.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
