/*
 * Created on 22 Feb 2016 ( Time 14:37:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.junggu.web.listitem;

import org.trams.junggu.bean.Server;
import org.trams.junggu.web.common.ListItem;

public class ServerListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ServerListItem(Server server) {
		super();

		this.value = ""
			 + server.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = server.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
